name: env_jax_2024
channels:
  - intel
  - nvidia
  - anaconda
  - fastai
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - aiohttp=3.8.3=py39h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.2=py39h06a4308_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - babel=2.11.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - basemap=1.2.2=py39h7980778_5
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_9
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.4=py39h06a4308_0
  - boost-cpp=1.73.0=h7f8727e_12
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2025.9.9=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - camb=1.3.5=py39h7f737d4_0
  - chex=0.1.5=py39h06a4308_0
  - cloudpickle=2.2.1=py39h06a4308_0
  - colorama=0.4.6=py39h06a4308_0
  - comm=0.1.2=py39h06a4308_0
  - cryptography=39.0.1=py39h9ce1e76_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - curl=8.1.1=h5eee18b_1
  - cython-blis=0.7.9=py39h7deecbd_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - diffmah=0.1.0=pyhd8ed1ab_0
  - dm-tree=0.1.7=py39h6a678d5_1
  - eigen=3.4.0=h00ab1b0_0
  - entrypoints=0.4=py39h06a4308_0
  - execnb=0.1.5=py_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.9=h6a678d5_0
  - fast-pt=3.1.0=pyh9f0ad1d_0
  - fastcore=1.5.29=py39h06a4308_1
  - ffmpeg=4.2.2=h20bf706_0
  - fftw=3.3.10=nompi_hf0379b8_106
  - flax=0.4.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h52c9d5c_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.3.3=py39h5eee18b_0
  - future=0.18.3=py39h06a4308_0
  - galsim=2.5.1=py39h3fe2f80_0
  - gast=0.4.0=pyhd3eb1b0_0
  - gcc=9.4.0=h192d537_9
  - gcc_impl_linux-64=9.4.0=h03d3576_15
  - gcc_linux-64=9.4.0=h391b98a_9
  - gdk-pixbuf=2.42.10=h5eee18b_0
  - geos=3.10.2=h9c3ff4c_0
  - gfortran=9.4.0=h2018a41_9
  - gfortran_impl_linux-64=9.4.0=h0003116_15
  - gfortran_linux-64=9.4.0=hf0ab688_9
  - ghapi=1.0.3=py_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py39heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - gobject-introspection=1.72.0=py39hbb6d50b_2
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h1b29801_1
  - grpc-cpp=1.46.1=h33aed49_1
  - gsl=2.7.1=h6e86dc7_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=hb67d8dd_3
  - halotools=0.8.1=py39h4661b88_2
  - harfbuzz=4.3.0=hf52aaf7_1
  - hdf4=4.2.13=h10796ff_1005
  - hdf5=1.10.6=h3ffc7dd_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py39h06a4308_0
  - importlib_metadata=6.0.0=hd3eb1b0_0
  - importlib_resources=6.1.0=py39h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.19.2=py39hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jax=0.3.25=py39h06a4308_0
  - jaxlib=0.3.25=py39h6a678d5_1
  - jedi=0.18.1=py39h06a4308_1
  - jinja2=3.1.2=py39h06a4308_0
  - jpeg=9e=h5eee18b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py39h06a4308_0
  - jupyter_server=1.23.4=py39h06a4308_0
  - jupyterlab=3.2.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py39h06a4308_0
  - jupyterlab_widgets=3.0.5=py39h06a4308_0
  - keras=2.11.0=py39h06a4308_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - krb5=1.20.1=h568e23c_1
  - lame=3.100=h7b6447c_0
  - langcodes=3.3.0=pyhd3eb1b0_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=12_linux64_mkl
  - libboost=1.73.0=h28710b8_12
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcblas=3.9.0=12_linux64_mkl
  - libcurl=8.1.1=h91b91d3_1
  - libcusparse=11.7.3.50=h6aaafad_0
  - libdeflate=1.17=h5eee18b_0
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-devel_linux-64=9.4.0=hd854feb_15
  - libgcc-ng=12.2.0=h65d4601_19
  - libgd=2.3.3=h6a678d5_2
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - liblapack=3.9.0=12_linux64_mkl
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm11=11.1.0=h9e868ea_6
  - libnetcdf=4.8.1=h8322cc2_2
  - libnghttp2=1.52.0=ha637b67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=h37d81fd_1
  - libprotobuf=3.20.3=he621ea3_0
  - librsvg=2.54.4=h36cc946_2
  - libsanitizer=9.4.0=h79bfe98_15
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libtool=2.4.6=h6a678d5_1009
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - libzip=1.8.0=h4de3113_1
  - lsstdesc.coord=1.3.0=py39h7633fee_1
  - lz4-c=1.9.4=h6a678d5_0
  - markdown=3.4.1=py39h06a4308_0
  - matplotlib-base=3.8.0=py39h1128e8f_0
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mkl=2021.4.0=intel_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mock=4.0.3=pyhd3eb1b0_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpi=1.0=mpich
  - mpi4py=3.1.3=py39h32b9844_1
  - mpich=4.0.1=h846660c_100
  - mpmath=1.2.1=py39h06a4308_0
  - msgpack-python=1.0.3=py39hd09550d_0
  - multidict=6.0.2=py39h5eee18b_0
  - munkres=1.1.4=py_0
  - nbclassic=0.5.5=py39h06a4308_0
  - nbclient=0.5.13=py39h06a4308_0
  - nbdev=2.3.12=py_0
  - nbformat=5.7.0=py39h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py39h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - notebook=6.5.4=py39h06a4308_0
  - notebook-shim=0.2.2=py39h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numexpr=2.8.4=py39he184ba9_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1w=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - optax=0.1.4=py39h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.50.7=h05da053_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.4=py39h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - ply=3.11=py39h06a4308_0
  - poppler=22.12.0=h381b16e_0
  - poppler-data=0.4.11=h06a4308_1
  - proj=8.2.1=ha227179_0
  - prometheus_client=0.14.1=py39h06a4308_0
  - promise=2.3=py39h06a4308_0
  - psutil=5.9.0=py39h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pybind11=2.11.1=py39h7633fee_2
  - pybind11-global=2.11.1=py39h7633fee_2
  - pyccl=2.3.0=py39h4dbe252_1
  - pydoe2=1.3.0=py_0
  - pyerfa=2.0.0=py39h27cfd23_0
  - pygments=2.15.1=py39h06a4308_1
  - pyjwt=2.4.0=py39h06a4308_0
  - pynndescent=0.5.10=py39h06a4308_0
  - pyopenssl=23.0.0=py39h06a4308_0
  - pyproj=3.4.1=py39hb83c990_0
  - pyqt=5.15.7=py39h6a678d5_1
  - pyqt5-sip=12.11.0=py39h6a678d5_1
  - pyrsistent=0.18.0=py39heee7806_0
  - pyshp=2.1.3=pyhd3eb1b0_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.17=h7a1cb2a_0
  - python-fastjsonschema=2.16.2=py39h06a4308_0
  - python-flatbuffers=2.0=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pyyaml=6.0=py39h5eee18b_1
  - pyzmq=24.0.1=py39headdf64_1
  - qt-main=5.15.2=h327a75a_7
  - qt-webengine=5.15.9=hd2b0992_4
  - qtwebkit=5.212=h4eab89a_4
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - seaborn=0.11.2=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - shap=0.40.0=py39hde0f152_1
  - shellingham=1.5.0=py39h06a4308_0
  - sip=6.6.2=py39h6a678d5_0
  - slicer=0.0.7=pyhd3eb1b0_0
  - smart_open=5.2.1=py39h06a4308_0
  - snappy=1.1.9=h295c915_0
  - sniffio=1.2.0=py39h06a4308_1
  - spacy-legacy=3.0.12=py39h06a4308_0
  - spacy-loggers=1.0.4=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.11.1=py39h06a4308_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard-data-server=0.6.1=py39h52d8a92_0
  - tensorflow=2.11.0=mkl_py39hea27e05_0
  - tensorflow-base=2.11.0=mkl_py39he5f8e37_0
  - tensorflow-datasets=1.2.0=py39h06a4308_0
  - tensorflow-metadata=0.14.0=pyhe6710b0_1
  - terminado=0.17.1=py39h06a4308_0
  - thinc=8.1.10=py39h3c18c91_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.12.0=py39h06a4308_0
  - tornado=6.2=py39h5eee18b_0
  - typing_extensions=4.6.3=py39h06a4308_0
  - umap-learn=0.5.2=py39hf3d152e_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - websocket-client=0.58.0=py39h06a4308_4
  - widgetsnbextension=3.5.2=py39h06a4308_0
  - wrapt=1.14.1=py39h5eee18b_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.8.1=py39h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
    - about-time==4.2.1
    - absl-py==0.15.0
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - alabaster==0.7.12
    - algopy==0.5.7
    - alibi==0.9.4
    - alive-progress==3.2.0
    - altair==4.2.0
    - annotated-types==0.7.0
    - anyio==4.8.0
    - apptools==5.2.0
    - arrow==1.2.3
    - arviz==0.11.2
    - asgiref==3.8.1
    - astro-sedpy==0.3.0
    - astropy==4.3.1
    - attrs==25.1.0
    - autograd==1.7.0
    - backoff==2.2.1
    - bcrypt==4.2.1
    - beautifulsoup4==4.11.0
    - bigfile==0.1.51
    - black==22.3.0
    - blessed==1.19.1
    - build==1.2.2.post1
    - cachetools==4.2.4
    - cairocffi==1.3.0
    - cairosvg==2.5.2
    - catalogue==2.0.8
    - celluloid==0.2.0
    - certifi==2021.10.8
    - cffi==1.15.0
    - cftime==1.6.2
    - charset-normalizer==2.0.7
    - chroma-hnswlib==0.7.6
    - chromadb==0.6.3
    - ci-info==0.3.0
    - clang==5.0
    - click==8.1.8
    - cma==3.2.2
    - cmake==3.27.5
    - codecov==2.1.12
    - coloredlogs==15.0.1
    - colorful==0.5.4
    - colossus==1.3.2
    - common==0.1.2
    - commonmark==0.9.1
    - confection==0.1.0
    - configobj==5.0.8
    - configparser==7.1.0
    - configspace==0.5.0
    - contourpy==1.1.0
    - corner==2.2.1
    - corrfunc==2.5.3
    - coverage==6.3.2
    - croniter==1.3.15
    - cssselect2==0.4.1
    - cycler==0.11.0
    - cymem==2.0.7
    - cython==0.29.24
    - dataclasses-json==0.6.7
    - datasets==3.3.2
    - dateutils==0.6.12
    - deap==1.3.1
    - deepdiff==6.3.0
    - deepspace==0.0.6
    - defusedxml==0.7.1
    - deprecated==1.2.13
    - descqa==2.0.0-0.7.0
    - dh-scikit-optimize==0.9.5
    - dill==0.3.5.1
    - distro==1.9.0
    - docopt==0.6.2
    - docutils==0.16
    - drawsvg==1.9.0
    - dsps==0.1.0
    - durationpy==0.9
    - duste==0.0.2
    - dynesty==2.0.0
    - easyquery==0.4.0
    - emulator-utils==0.0.0
    - envisage==7.0.3
    - et-xmlfile==1.1.0
    - etelemetry==0.3.1
    - exceptiongroup==1.2.2
    - fastapi==0.115.8
    - filelock==3.12.2
    - fitz==0.0.1.dev2
    - flatbuffers==1.12
    - flowpm==0.1.2.dev252+g8f9415b.d20231030
    - fonttools==4.40.0
    - fsps==0.4.1
    - fsps-wrapper==1.0
    - fsspec==2023.6.0
    - gcr==0.9.2
    - gcrcatalogs==1.5.0
    - getdist==1.3.4
    - gin-config==0.4.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-api-core==2.7.1
    - google-auth==2.3.0
    - google-auth-oauthlib==0.4.6
    - googleapis-common-protos==1.68.0
    - gprof2dot==2022.7.29
    - gpustat==1.0.0b1
    - gpy==1.13.2
    - grapheme==0.6.0
    - greenlet==3.1.1
    - grpcio==1.41.0
    - h11==0.14.0
    - h5py==3.9.0
    - haccytrees==0.9.0
    - healpy==1.16.2
    - hiredis==2.0.0
    - hpo-uq==1.3.10
    - httpcore==1.0.7
    - httplib2==0.22.0
    - httptools==0.6.4
    - httpx==0.28.1
    - httpx-sse==0.4.0
    - huggingface-hub==0.29.1
    - humanfriendly==10.0
    - imagecodecs==2024.12.30
    - imageio==2.13.3
    - imagesize==1.3.0
    - importlib-metadata==8.5.0
    - importlib-resources==6.0.0
    - iniconfig==1.1.1
    - inquirer==3.1.3
    - ipython==8.12.3
    - isodate==0.6.1
    - itsdangerous==2.1.2
    - jeepney==0.8.0
    - jiter==0.8.2
    - joblib==1.3.1
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - keyring==23.5.0
    - kiwisolver==1.3.2
    - kubernetes==32.0.1
    - langchain==0.3.19
    - langchain-community==0.3.18
    - langchain-core==0.3.39
    - langchain-text-splitters==0.3.6
    - langsmith==0.3.11
    - lazy-loader==0.3
    - liac-arff==2.5.0
    - libclang==13.0.0
    - lightning==2.0.3
    - lightning-cloud==0.5.37
    - lightning-utilities==0.8.0
    - lit==16.0.5.post0
    - litellm==1.61.16
    - llvmlite==0.39.1
    - looseversion==1.3.0
    - lsstdesc-coord==1.2.3
    - lxml==4.8.0
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - marshmallow==3.26.1
    - matplotlib==3.8.2
    - mayavi==4.8.1
    - mdurl==0.1.2
    - mesh-tensorflow==0.1.19
    - minio==7.1.5
    - mistune==3.2.0
    - mmh3==5.1.0
    - monotonic==1.6
    - mpipartition==1.0.5
    - multiprocess==0.70.13
    - murmurhash==1.0.9
    - mypy-extensions==0.4.3
    - nbconvert==5.6.1
    - nbsphinx==0.8.8
    - netcdf4==1.6.1
    - networkx==3.1
    - nibabel==5.2.1
    - nipype==1.8.6
    - numba==0.54.1
    - numdifftools==0.9.40
    - numpy==1.19.5
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-ml-py3==7.352.0
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.1.1
    - onnxruntime==1.19.2
    - openai==1.64.0
    - opencensus==0.8.0
    - opencensus-context==0.1.2
    - opencv-python==4.9.0.80
    - openml==0.12.2
    - openpyxl==3.0.10
    - opentelemetry-api==1.30.0
    - opentelemetry-exporter-otlp-proto-common==1.30.0
    - opentelemetry-exporter-otlp-proto-grpc==1.30.0
    - opentelemetry-instrumentation==0.51b0
    - opentelemetry-instrumentation-asgi==0.51b0
    - opentelemetry-instrumentation-fastapi==0.51b0
    - opentelemetry-proto==1.30.0
    - opentelemetry-sdk==1.30.0
    - opentelemetry-semantic-conventions==0.51b0
    - opentelemetry-util-http==0.51b0
    - ordered-set==4.1.0
    - orjson==3.10.15
    - overrides==7.7.0
    - packaging==24.2
    - pandas==2.0.3
    - paramz==0.9.6
    - pathlib==1.0.1
    - pathos==0.2.9
    - pathspec==0.9.0
    - pathy==0.10.2
    - patsy==0.5.2
    - pickle5==0.0.11
    - pillow==9.5.0
    - pipreqs==0.5.0
    - pkginfo==1.8.2
    - platformdirs==2.5.1
    - plotly==5.8.0
    - pluggy==1.0.0
    - posthog==3.15.1
    - pox==0.3.1
    - ppft==1.7.6.5
    - preshed==3.0.8
    - prompt-toolkit==3.0.52
    - protobuf==3.18.1
    - prov==2.0.1
    - py==1.11.0
    - py-spy==0.3.11
    - pyaml==21.10.1
    - pyarrow==19.0.1
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pydantic-settings==2.8.0
    - pydata-sphinx-theme==0.8.1
    - pydeck==0.7.1
    - pydot==1.4.2
    - pyface==8.0.0
    - pygio==0.1
    - pymoo==0.6.1.3
    - pympler==1.0.1
    - pyparsing==3.0.6
    - pypika==0.48.9
    - pyproject-hooks==1.2.0
    - pytest==7.1.1
    - pytest-astropy-header==0.2.2
    - pytest-cov==3.0.0
    - python-dateutil==2.8.2
    - python-dotenv==1.0.1
    - python-editor==1.0.4
    - python-multipart==0.0.6
    - pytorch-lightning==2.0.3
    - pytz==2023.3
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.4.1
    - pyxnat==1.6.2
    - qtconsole==5.3.0
    - qtpy==2.0.1
    - ray==1.11.0
    - rdflib==6.3.2
    - readchar==4.0.5
    - readme-renderer==34.0
    - redis==4.2.2
    - referencing==0.36.2
    - regex==2023.6.3
    - requests==2.31.0
    - requests-toolbelt==1.0.0
    - rfc3986==2.0.0
    - rich==13.4.2
    - rpds-py==0.23.1
    - rstcheck==3.3.1
    - safetensors==0.5.2
    - salib==1.4.5
    - scikit-image==0.21.0
    - scikit-learn==1.3.0
    - scipy==1.11.2
    - secretstorage==3.3.1
    - semver==2.13.0
    - sentence-transformers==3.4.1
    - setuptools==68.0.0
    - simplejson==3.19.3
    - six==1.16.0
    - sklearn==0.0
    - smart-open==6.3.0
    - smmap==5.0.0
    - snowballstemmer==2.2.0
    - soupsieve==2.3.2
    - spacy==3.6.0
    - spacy-lookups-data==1.0.3
    - speclite==0.19
    - sphinx==3.5.4
    - sphinx-book-theme==0.3.2
    - sphinx-copybutton==0.5.0
    - sphinx-togglebutton==0.3.1
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sqlalchemy==2.0.38
    - srsly==2.4.7
    - starlette==0.45.3
    - starsessions==1.3.0
    - statsmodels==0.13.2
    - streamlit==1.8.1
    - tenacity==9.0.0
    - tensorboard==2.7.0
    - tensorboard-plugin-wit==1.8.0
    - tensorflow-addons==0.14.0
    - tensorflow-estimator==2.6.0
    - tensorflow-gpu==2.6.0
    - tensorflow-io-gcs-filesystem==0.23.1
    - tensorflow-probability==0.14.1
    - termcolor==1.1.0
    - tfds-nightly==4.5.2.dev202202020043
    - threadpoolctl==3.1.0
    - tifffile==2023.7.4
    - tiktoken==0.9.0
    - tinycss2==1.1.1
    - tinydb==4.7.0
    - tokenizers==0.21.0
    - tomli==2.0.1
    - torch==2.0.1
    - torchaudio==2.0.2
    - torchinfo==1.8.0
    - torchmetrics==0.11.4
    - torchvision==0.15.2
    - tqdm==4.67.1
    - traitlets==5.9.0
    - traits==6.3.2
    - traitsui==7.4.3
    - transformers==4.49.0
    - treecorr==4.3.3
    - triton==2.0.0
    - twine==4.0.0
    - typeguard==2.13.0
    - typer==0.9.0
    - typing-extensions==3.10.0.2
    - typing-inspect==0.9.0
    - tzdata==2022.1
    - tzlocal==4.2
    - umachine-pyio==0.1
    - urllib3==1.26.20
    - uvicorn==0.22.0
    - uvloop==0.21.0
    - validators==0.18.2
    - vega==1.3.0
    - vega-datasets==0.9.0
    - vtk==9.2.6
    - wasabi==1.1.2
    - watchdog==2.1.7
    - watchfiles==1.0.4
    - webencodings==0.5.1
    - websockets==11.0.3
    - werkzeug==2.0.2
    - wheel==0.37.0
    - wurlitzer==3.1.1
    - xarray==2022.9.0
    - xgboost==1.5.2
    - xmltodict==0.12.0
    - xxhash==3.5.0
    - yarg==0.1.9
    - zipp==3.16.0
    - zstandard==0.23.0
prefix: /home/nramachandra/anaconda3/envs/env_jax_2024
